<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDemoTable extends Migration
{

    public function up()
    {
        Schema::connection('umas')->create('MT_CLIENT', function (Blueprint $table) {
            $table->string('CODCLI',30)->nullable();
            $table->string('DIG',1)->nullable();
            $table->string('PATERNO',100)->nullable();
            $table->string('MATERNO',100)->nullable();
            $table->string('NOMBRE',200)->nullable();
            $table->string('SEXO',1)->nullable();
            $table->string('NACIONALIDAD',30)->nullable();
            $table->string('DOBLENACION',32)->nullable();
            $table->string('TIPOVISA',32)->nullable();
            $table->string('PASAPORTE',50)->nullable();
            $table->dateTime('FECNAC')->nullable();
            $table->string('CODESTCIVIL',30)->nullable();
            $table->decimal('CODSISSALUD',10,0)->nullable();
            $table->string('DIRPROC',110)->nullable();
            $table->string('CIUPROC',30)->nullable();
            $table->string('COMUNAPRO',30)->nullable();
            $table->string('FONOPROC',32)->nullable();
            $table->string('DIRACTUAL',110)->nullable();
            $table->string('COMUNA',30)->nullable();
            $table->string('CIUDADACT',30)->nullable();
            $table->string('FONOACT',20)->nullable();
            $table->decimal('COLEGIO',10,0)->nullable();
            $table->string('ANOEEM',4)->nullable();
            $table->string('NOTAEM',4)->nullable();
            $table->string('UNIVERSIDAD',4)->nullable();
            $table->decimal('ES_PAIS',2,0)->nullable();
            $table->string('ES_CIUDAD',30)->nullable();
            $table->string('ES_CARR',60)->nullable();
            $table->string('ES_TITULADO',1)->nullable();
            $table->string('ES_TITULO',60)->nullable();
            $table->decimal('ES_ULANO',4,0)->nullable();
            $table->decimal('ES_SEMAP',4,0)->nullable();
            $table->string('AL_ACTIVI',60)->nullable();
            $table->string('AL_EMP',60)->nullable();
            $table->string('AL_DIRCOM',60)->nullable();
            $table->string('AL_FONO',30)->nullable();
            $table->string('CODAPOD',30)->nullable();
            $table->string('DOCUMENTADO',1)->nullable();
            $table->dateTime('FECDOC')->nullable();
            $table->string('ARAN_BAS',1)->nullable();
            $table->dateTime('FECARBAS')->nullable();
            $table->string('CIUDNAC',30)->nullable();
            $table->decimal('ANO',4,0)->nullable();
            $table->string('EMERGENCIA',70)->nullable();
            $table->string('FONOEMERG',30)->nullable();
            $table->string('USUARIO',8)->nullable();
            $table->dateTime('FECMOD')->nullable();
            $table->string('RUTCLI',1)->nullable();
            $table->string('DOLENCIA',70)->nullable();
            $table->string('MAIL',100)->nullable();
            $table->string('CONTRAINDICACION',70)->nullable();
            $table->integer('ANOINGRESO')->nullable();
            $table->smallInteger('PERIODO')->nullable();
            $table->string('VIGENTE',1)->nullable();
            $table->dateTime('FEC_MAT')->nullable();
            $table->dateTime('FECING')->nullable();
            $table->string('CODAVAL',30)->nullable();
            $table->string('CODASEGURADO',30)->nullable();
            $table->string('VIADMISION',10)->nullable();
            $table->string('ACHSCCAF18',1)->nullable();
            $table->string('LOCALIDADACT',30)->nullable();
            $table->string('LOCALIDADPRO',30)->nullable();
            $table->string('MATRICULABLE',1)->nullable();
            $table->string('DEUDA_BIBLIOTECA',1)->nullable();
            $table->string('CODMEDIO',10)->nullable();
            $table->string('VIACONSULTA',10)->nullable();
            $table->string('DESBL_TOMARAMOS',1)->nullable();
            $table->string('CATEGORIA',10)->nullable();
            $table->decimal('CODEMPRESA',10,0)->nullable();
            $table->string('CODTRAMO')->nullable();
            $table->string('CODMOTIVO')->nullable();
            $table->string('REGLICEM')->nullable();
            $table->string('NUMINSCRIPCION')->nullable();
            $table->string('FECHAINSCRIP')->nullable();
            $table->string('CIRCUNSCRIPCION')->nullable();
            $table->string('ANOINSCRIP')->nullable();
            $table->string('DEUDA')->nullable();
            $table->string('NROHIJOS')->nullable();
            $table->string('ATRABAJADO')->nullable();
            $table->string('CELULARACT')->nullable();
            $table->string('ES_PROMEDIONOTAS')->nullable();
            $table->string('ES_UNIVERSIDADEXT')->nullable();
            $table->string('TIPOMERITO')->nullable();
            $table->string('LUGARCURSO')->nullable();
            $table->string('DESCMERITO')->nullable();
            $table->string('TIPODEPORTE')->nullable();
            $table->string('DESCDEPORTE')->nullable();
            $table->string('CARRERAORIGEN')->nullable();
            $table->string('CARRERADESTINO')->nullable();
            $table->string('INSTITUCION')->nullable();
            $table->string('PAIS')->nullable();
            $table->string('Es_Iniano')->nullable();
            $table->string('SENCE')->nullable();
            $table->string('DATOS_P')->nullable();
            $table->string('FECINIPAS')->nullable();
            $table->string('FECFINPAS')->nullable();
            $table->string('Mail_Inst')->nullable();
            $table->string('Visible_Egresado')->nullable();
            $table->string('Recibe_informativos')->nullable();
            $table->string('AREAPROC')->nullable();
            $table->string('AREAACT')->nullable();
            $table->string('CAE')->nullable();
            $table->string('CELULAR')->nullable();
            $table->string('BecaNuevoMilenio')->nullable();
            $table->string('BecaExcelencia')->nullable();
            $table->string('OTRABECA')->nullable();
            $table->string('GLOSACAE')->nullable();
            $table->string('FECHA_TRASPASO')->nullable();
            $table->string('Clave_Mail_Inst')->nullable();
            $table->string('N_PERS_HOGAR')->nullable();
            $table->string('ING_BRUTO_FAMILIAR')->nullable();
            $table->string('FECHA_DEFUNCION')->nullable();
            $table->string('al_cargo')->nullable();
            $table->string('TRASPASOCONTA')->nullable();
            $table->string('TipoDocumento')->nullable();
            $table->string('CodModalidad')->nullable();
            $table->string('CodEspecialidad')->nullable();
            $table->string('CODRELACION')->nullable();
            $table->string('CODTIPORELACION')->nullable();
            $table->string('OBSERVACION')->nullable();
            $table->string('FECRELACION')->nullable();
            $table->string('TipoResidencia')->nullable();
            $table->string('pref_correo')->nullable();
            $table->string('pref_direccion')->nullable();
            $table->string('pref_telefono')->nullable();
        });
    }

    public function down()
    {
        Schema::connection('umas')->dropIfExists('demo');
    }

}
