<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMTCLIENTTable extends Migration
{

    public function up()
    {
        Schema::connection('umas')->create('MT_CLIENT', function (Blueprint $table) {
            $table->string('CODCLI',30)->nullable();
            $table->string('DIG',1)->nullable();
            $table->string('PATERNO',100)->nullable();
            $table->string('MATERNO',100)->nullable();
            $table->string('NOMBRE',200)->nullable();
            $table->string('SEXO',1)->nullable();
            $table->string('NACIONALIDAD',30)->nullable();
            $table->string('DOBLENACION',32)->nullable();
            $table->string('TIPOVISA',32)->nullable();
            $table->string('PASAPORTE',50)->nullable();
            $table->dateTime('FECNAC')->nullable();
            $table->string('CODESTCIVIL',30)->nullable();
            $table->decimal('CODSISSALUD',10,0)->nullable();
            $table->string('DIRPROC',110)->nullable();
            $table->string('CIUPROC',30)->nullable();
            $table->string('COMUNAPRO',30)->nullable();
            $table->string('FONOPROC',32)->nullable();
            $table->string('DIRACTUAL',110)->nullable();
            $table->string('COMUNA',30)->nullable();
            $table->string('CIUDADACT',30)->nullable();
            $table->string('FONOACT',20)->nullable();
            $table->decimal('COLEGIO',10,0)->nullable();
            $table->string('ANOEEM',4)->nullable();
            $table->string('NOTAEM',4)->nullable();
            $table->string('UNIVERSIDAD',4)->nullable();
            $table->decimal('ES_PAIS',2,0)->nullable();
            $table->string('ES_CIUDAD',30)->nullable();
            $table->string('ES_CARR',60)->nullable();
            $table->string('ES_TITULADO',1)->nullable();
            $table->string('ES_TITULO',60)->nullable();
            $table->decimal('ES_ULANO',4,0)->nullable();
            $table->decimal('ES_SEMAP',4,0)->nullable();
            $table->string('AL_ACTIVI',60)->nullable();
            $table->string('AL_EMP',60)->nullable();
            $table->string('AL_DIRCOM',60)->nullable();
            $table->string('AL_FONO',30)->nullable();
            $table->string('CODAPOD',30)->nullable();
            $table->string('DOCUMENTADO',1)->nullable();
            $table->dateTime('FECDOC')->nullable();
            $table->string('ARAN_BAS',1)->nullable();
            $table->dateTime('FECARBAS')->nullable();
            $table->string('CIUDNAC',30)->nullable();
            $table->decimal('ANO',4,0)->nullable();
            $table->string('EMERGENCIA',70)->nullable();
            $table->string('FONOEMERG',30)->nullable();
            $table->string('USUARIO',8)->nullable();
            $table->dateTime('FECMOD')->nullable();
            $table->string('RUTCLI',1)->nullable();
            $table->string('DOLENCIA',70)->nullable();
            $table->string('MAIL',100)->nullable();
            $table->string('CONTRAINDICACION',70)->nullable();
            $table->integer('ANOINGRESO')->nullable();
            $table->smallInteger('PERIODO')->nullable();
            $table->string('VIGENTE',1)->nullable();
            $table->dateTime('FEC_MAT')->nullable();
            $table->dateTime('FECING')->nullable();
            $table->string('CODAVAL',30)->nullable();
            $table->string('CODASEGURADO',30)->nullable();
            $table->string('VIADMISION',10)->nullable();
            $table->string('ACHSCCAF18',1)->nullable();
            $table->string('LOCALIDADACT',30)->nullable();
            $table->string('LOCALIDADPRO',30)->nullable();
            $table->string('MATRICULABLE',1)->nullable();
            $table->string('DEUDA_BIBLIOTECA',1)->nullable();
            $table->string('CODMEDIO',10)->nullable();
            $table->string('VIACONSULTA',10)->nullable();
            $table->string('DESBL_TOMARAMOS',1)->nullable();
            $table->string('CATEGORIA',10)->nullable();
            $table->integer('CODEMPRESA')->nullable();
            $table->decimal('CODTRAMO',5,0)->nullable();
            $table->decimal('CODMOTIVO',5,0)->nullable();
            $table->string('REGLICEM',20)->nullable();
            $table->string('NUMINSCRIPCION',20)->nullable();
            $table->dateTime('FECHAINSCRIP')->nullable();
            $table->string('CIRCUNSCRIPCION',20)->nullable();
            $table->integer('ANOINSCRIP')->nullable();
            $table->integer('DEUDA')->nullable();
            $table->integer('NROHIJOS')->nullable();
            $table->integer('ATRABAJADO')->nullable();
            $table->string('CELULARACT',30)->nullable();
            $table->decimal('ES_PROMEDIONOTAS',6,2)->nullable();
            $table->string('ES_UNIVERSIDADEXT',50)->nullable();
            $table->integer('TIPOMERITO')->nullable();
            $table->integer('LUGARCURSO')->nullable();
            $table->string('DESCMERITO',50)->nullable();
            $table->string('TIPODEPORTE',50)->nullable();
            $table->string('DESCDEPORTE',50)->nullable();
            $table->string('CARRERAORIGEN',10)->nullable();
            $table->string('CARRERADESTINO',10)->nullable();
            $table->string('INSTITUCION',10)->nullable();
            $table->decimal('PAIS',4,0)->nullable();
            $table->decimal('Es_Iniano',4,0)->nullable();
            $table->integer('SENCE')->nullable();
            $table->string('DATOS_P',1)->nullable();
            $table->dateTime('FECINIPAS')->nullable();
            $table->dateTime('FECFINPAS')->nullable();
            $table->string('Mail_Inst',100)->nullable();
            $table->string('Visible_Egresado',2)->nullable();
            $table->string('Recibe_informativos',1)->nullable();
            $table->integer('AREAPROC')->nullable();
            $table->integer('AREAACT')->nullable();
            $table->integer('CAE')->nullable();
            $table->string('CELULAR',10)->nullable();
            $table->integer('BecaNuevoMilenio')->nullable();
            $table->integer('BecaExcelencia')->nullable();
            $table->string('OTRABECA',30)->nullable();
            $table->string('GLOSACAE',30)->nullable();
            $table->dateTime('FECHA_TRASPASO')->nullable();
            $table->string('Clave_Mail_Inst',100)->nullable();
            $table->integer('N_PERS_HOGAR')->nullable();
            $table->decimal('ING_BRUTO_FAMILIAR',10,0)->nullable();
            $table->dateTime('FECHA_DEFUNCION')->nullable();
            $table->string('al_cargo',50)->nullable();
            $table->string('TRASPASOCONTA',2)->nullable();
            $table->smallInteger('TipoDocumento')->nullable();
            $table->string('CodModalidad',30)->nullable();
            $table->integer('CodEspecialidad')->nullable();
            $table->string('CODRELACION',30)->nullable();
            $table->string('CODTIPORELACION',30)->nullable();
            $table->string('OBSERVACION',200)->nullable();
            $table->dateTime('FECRELACION')->nullable();
            $table->smallInteger('TipoResidencia')->nullable();
            $table->string('pref_correo',20)->nullable();
            $table->string('pref_direccion',20)->nullable();
            $table->string('pref_telefono',20)->nullable();
        });
    }

    public function down()
    {
        Schema::connection('umas')->dropIfExists('MT_CLIENT');
    }

}
